# Generated by Django 6.0.6 on 2026-08-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamodel',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelta', 'Resuelta')], default='pendiente', max_length=20),
        ),
    ]
