# Generated by Django 6.0.6 on 2026-09-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventamodel',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ventamodel',
            name='metodo_envio',
            field=models.CharField(choices=[('retiro_local', 'Retiro en el local'), ('envio_domicilio', 'Envío a domicilio'), ('coordinar_entrega', 'Coordinar entrega')], max_length=20),
        ),
    ]
