# Generated by Django 6.0.6 on 2026-09-15 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_crear_tags'),
        ('ventas', '0002_ventamodel_numero_alter_ventamodel_metodo_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaitemmodel',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.productomodel'),
        ),
    ]
