# Generated by Django 6.0.6 on 2026-09-15 16:06

from django.db import migrations, models


def backfill_nombre_producto(apps, schema_editor):
    VentaItemModel = apps.get_model('ventas', 'VentaItemModel')
    for item in VentaItemModel.objects.select_related('producto').filter(nombre_producto__isnull=True):
        item.nombre_producto = item.producto.nombre
        item.save(update_fields=['nombre_producto'])


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_ventaitemmodel_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaitemmodel',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ventaitemmodel',
            name='promocion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(backfill_nombre_producto, reverse_backfill),
    ]
