# Generated by Django 6.0.6 on 2026-09-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_ventaitemmodel_nombre_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventamodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
