# Generated by Django 6.0.6 on 2026-09-20 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_ventamodel_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('mp_preference_id', models.CharField(blank=True, max_length=40, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('external_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='ventas.ventamodel')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'ventas_pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
