# Generated by Django 6.0.6 on 2026-06-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productomodel_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomodel',
            name='precio_transferencia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio con descuento por transferencia bancaria', max_digits=10, null=True),
        ),
    ]
