# Generated by Django 6.0.6 on 2026-06-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productomodel_precio_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomodel',
            name='precio_transferencia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio con descuento por transferencia bancaria', max_digits=10),
            preserve_default=False,
        ),
    ]
