# Generated by Django 6.0.6 on 2026-07-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_productomodel_precio_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomodel',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio final con promoción aplicada (para API y checkout)', max_digits=10),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='precio_transferencia_final',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio transferencia final con promoción aplicada (para filtros y display)', max_digits=10),
        ),
    ]
